myproject/core/urls.py
from django.conf.urls import patterns, url
from myproject.core.views import *
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    'myproject.core.views',
    url(r'^$', PersonList.as_view(), name='person_list'),
    url(r'^add/$', 'person_create', name='person_add'),
    url(r'^(?P<pk>\d+)/$', 'person_detail', name='person_detail'),
    url(r'^(?P<pk>\d+)/json/$', 'person_detail_json', name='person_detail_json'),
    url(r'^(?P<pk>\d+)/edit/$', 'person_update', name='person_edit'),
    url(r'^(?P<pk>\d+)/delete/$', 'person_delete', name='person_delete')
)

myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'myproject.core.views.home', name='home'),
    url(r'^person/', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
)

myproject/core/models.py
# -*- coding: utf-8 -*-
from django.db import models
from localflavor.br.br_states import STATE_CHOICES


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em', auto_now_add=True, auto_now=False)
    modified = models.DateTimeField(
        'modificado em', auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True


class Address(models.Model):
    address = models.CharField(u'endereço', max_length=100, blank=True)
    complement = models.CharField('complemento', max_length=100, blank=True)
    district = models.CharField('bairro', max_length=100, blank=True)
    city = models.CharField('cidade', max_length=100, blank=True)
    uf = models.CharField('UF', max_length=2,
                          choices=STATE_CHOICES, blank=True)
    cep = models.CharField('CEP', max_length=9, blank=True)

    class Meta:
        abstract = True


class Person(TimeStampedModel, Address):
    first_name = models.CharField('nome', max_length=50)
    last_name = models.CharField(
        'sobrenome', max_length=50, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    birthday = models.DateField('nascimento', null=True, blank=True)
    description = models.TextField(u'descrição', null=True, blank=True)
    child = models.PositiveIntegerField('filhos', null=True, blank=True)
    salary = models.DecimalField(u'salário', max_digits=6, decimal_places=2)
    network = models.ManyToManyField(
        'Social', verbose_name='rede social', null=True, blank=True)

    class Meta:
        ordering = ['first_name']
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    def __unicode__(self):
        return ' '.join(filter(None, [self.first_name, self.last_name]))

    full_name = property(__unicode__)

    @models.permalink
    def get_absolute_url(self):
        return ('core:person_detail', (), {'pk': self.pk})


class Social(models.Model):
    network = models.CharField('rede social', max_length=50, unique=True)

    class Meta:
        ordering = ['network']
        verbose_name = 'rede social'
        verbose_name_plural = 'redes sociais'

    def __unicode__(self):
        return self.network

myproject/core/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'email', 'birthday',
                  'description', 'child', 'salary',
                  'address', 'complement', 'district', 'city', 'uf', 'cep',
                  'network']

myproject/core/views.py
from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView
from django.views.generic import UpdateView, DeleteView
from .models import Person
from .forms import PersonForm


def home(request):
    return render(request, 'index.html')


class PersonList(ListView):
    model = Person
    paginate_by = 10


def person_detail_json(request, pk):
    data = Person.objects.filter(pk=pk)
    s = serializers.serialize("json", data)
    return HttpResponse(s)


person_detail = DetailView.as_view(model=Person)

person_create = CreateView.as_view(model=Person, form_class=PersonForm)

person_update = UpdateView.as_view(model=Person, form_class=PersonForm)

person_delete = DeleteView.as_view(model=Person, success_url=('/person/'))

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Django boilerplate">
  <meta name="author" content="rg3915">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">

  <title>
    {% block title %}Django{% endblock title %}
  </title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/social.css" %}">
  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <style type="text/css">
    body {
      padding-top: 50px;
      /*color: #5a5a5a;*/
    }
  </style>

</head>
<body>
  {% include "nav.html" %}
  <div id="wrap">
    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </div>
  {% include "footer.html" %}
</body>
</html>

myproject/core/templates/core/person_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}Person Detail{% endblock title %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="{% url home %}">Home</a> <span class="divider"></span></li>
  <li><a href="{% url core:person_list %}">Contatos</a> <span class="divider"></span></li>
  <li class="active">{{ object.full_name }}</li>
</ul>

<div class="col-lg-8">
  <div class="col-md-2 column">
    <img src="https://cdn4.iconfinder.com/data/icons/ionicons/512/icon-person-128.png" class="img-square" style="height: 100px;" />
  </div>
  <div class="col-md-offset-3 column">
    <h1>{{ object.full_name }}</h1>
    {% if object.email %}
      <h4><span class="glyphicon glyphicon-envelope"></span><a href="#"> {{ object.email }}</a></h4>
    {% endif %}
    <div class="social">
      <ul>
        {% for network in object.network.all %}
          {% if network.network == 'facebook' %}
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          {% endif %}
          {% if network.network == 'twitter' %}
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          {% endif %}
          {% if network.network == 'google-plus' %}
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          {% endif %}
          {% if network.network == 'github' %}
            <li><a href="#"><i class="fa fa-github"></i></a></li>
          {% endif %}
          {% if network.network == 'pinterest' %}
            <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
          {% endif %}
          {% if network.network == 'linkedin' %}
            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          {% endif %}
          {% if network.network == 'instagram' %}
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>
          {% endif %}
          {% if network.network == 'skype' %}
            <li><a href="#"><i class="fa fa-skype"></i></a></li>
          {% endif %}
          {% if network.network == 'slack' %}
            <li><a href="#"><i class="fa fa-slack"></i></a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>

  </br>

  <table class="table table-user-information">
    <tbody>
      {% if object.birthday %}
        <tr>
          <th class="col-md-3 text-right"><span class="fa fa-birthday-cake"></span></th>
          <td>{{ object.birthday }}</td>
        </tr>
      {% else %}
        <tr>
          <th class="col-md-3 text-right"><span class="fa fa-birthday-cake"></span></th>
          <td>---</td>
        </tr>
      {% endif %}

      {% if object.address %}
        <tr>
          <th class="col-md-3 text-right"><span class="glyphicon glyphicon-map-marker"></span></th>
          <td>{{ object.address }}
            {% if object.complement %} - {{ object.complement }}{% endif %}
            {% if object.district %} - {{ object.district }}{% endif %}
          </td>
        </tr>
        <tr>
          <th class="col-md-3 text-right"></th>
          <td>
            {% if object.city %}{{ object.city }}{% endif %}
            {% if object.uf %} - {{ object.uf }}{% endif %}
            {% if object.cep %} - {{ object.cep }}{% endif %}
          </td>
        </tr>
      {% endif %}
      <tr>
        <th class="col-md-3 text-right">Descrição</th>
          <td>{{ object.description }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Filhos</th>
          <td>{{ object.child }}</td>
      </tr>
      <tr>
        <th class="col-md-3 text-right">Salário</th>
          <td>R$ {{ object.salary }}</td>
      </tr>

    </tbody>
  </table>

  <!-- edit -->
  <a href="{% url core:person_edit person.pk %}">
      <button id="edit_person" type="button" class="btn btn-success">
          <span class="fa fa-pencil"></span> Editar
      </button>
  </a>
  <!-- delete with modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
      <span class="fa fa-times"></span> Excluir
  </button>
  <!-- json -->
  <a href="{% url core:person_detail_json person.pk %}">
      <button type="button" class="btn btn-warning">
          <span class="fa fa-code"></span> Json
      </button>
  </a>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Confirmar</h4>
      </div>
        <form action="{% url core:person_delete person.id %}" method="POST">
      <div class="modal-body">
          {% csrf_token %}
          Deseja mesmo deletar "{{ object }}"?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        <input type="submit" class="btn btn-danger" value="Deletar" />
      </div>
        </form>
    </div>
  </div>
</div>


{% endblock content %}

myproject/core/templates/core/person_form.html
{% extends "base.html" %}

{% load bootstrap %}

{% block title %}Person Form{% endblock title %}

{% block content %}

<form class="form-horizontal col-sm-6" action="." method="POST">
    <legend>Novo Contato</legend>
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    
    <div class="form-group">
      <div class="col-sm-2 col-sm-offset-2">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </div>
</form>

{% endblock content %}

myproject/core/templates/core/person_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Contatos{% endblock title %}

{% block content %}

<form class="navbar-form navbar-right" action="." method="get">
    <!-- add -->
    <a href="{% url core:person_add %}">
        <button id="new" type="button" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus"></span> Adicionar
        </button>
    </a>
    <!-- search form -->
    <div class="form-group">
      <input id="search_box" name="search_box" type="text" placeholder="Localizar..." class="form-control">
      <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
  </div>
</form>

<div class="page-header">
<h2><h2><i class="fa fa-user"></i> Lista de Contatos</h2>
</div>

<div>
{% if person_list %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Redes sociais</th>
        <th class="text-center">Filhos</th>
        <th>Salário</th>
        <th>UF</th>
      </tr>
    </thead>
    <tbody>
    {% for person in person_list %}
      <tr>
        <td><a href="{{ person.get_absolute_url }}">{{ person.full_name }}</a></td>
        <td>{{ person.email }}</td>
        <td>
        <div class="social mini">
          {% for network in person.network.all %}
            {% if network.network == 'facebook' %}
              <a href="#"><i class="fa fa-facebook"></i></a>
            {% endif %}
            {% if network.network == 'twitter' %}
              <a href="#"><i class="fa fa-twitter"></i></a>
            {% endif %}
            {% if network.network == 'google-plus' %}
              <a href="#"><i class="fa fa-google-plus"></i></a>
            {% endif %}
            {% if network.network == 'github' %}
              <a href="#"><i class="fa fa-github"></i></a>
            {% endif %}
            {% if network.network == 'pinterest' %}
              <a href="#"><i class="fa fa-pinterest"></i></a>
            {% endif %}
            {% if network.network == 'linkedin' %}
              <a href="#"><i class="fa fa-linkedin"></i></a>
            {% endif %}
            {% if network.network == 'instagram' %}
              <a href="#"><i class="fa fa-instagram"></i></a>
            {% endif %}
            {% if network.network == 'skype' %}
              <a href="#"><i class="fa fa-skype"></i></a>
            {% endif %}
            {% if network.network == 'slack' %}
              <a href="#"><i class="fa fa-slack"></i></a>
            {% endif %}
          {% endfor %}
        </div>
        </td>
        <td class="text-center">{{ person.child }}</td>
        <td>{{ person.salary }}</td>
        <td>{{ person.get_uf_display }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p class="alert alert-warning">Sem itens na lista.</p>
{% endif %}
</div>

<hr>
<div>
<h4><b>Total:</b> {{ page_obj.paginator.count }} contato{{ page_obj.paginator.count|pluralize }}</h4>
</div>

{% include "pagination.html" %}

{% endblock content %}

myproject/core/templates/footer.html
<div id="footer">
  <div class="container">
    <p class="credit pull-left">Example by <a href="https://github.com/rg3915/">Régis da Silva</a> &copy; 2016 &middot; <a href="">download</a></p>
    <div class="socialfooter pull-center">
      <ul>
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
        <li><a href="#"><i class="fa fa-skype"></i></a></li>
        <li><a href="#"><i class="fa fa-slack"></i></a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <div class="jumbotron">
    <h1>Bem vindo!</h1>
    <a href="{% url core:person_add %}">
      <button id="new_customer" type="button" class="btn btn-primary">
        <span class="glyphicon glyphicon-plus"></span> Cadastre-se
      </button>
    </a>
  </div>
{% endblock content %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url home %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="{% url core:person_list %}"><span class="fa fa-users"></span> Lista de Contatos</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url admin:index %}"><span class="fa fa-drupal"></span> Admin</a></li>
      </ul>
    </div>
  </div>
</div>

myproject/core/templates/pagination.html
<!-- pagination -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% endif %}
      {% for pg in page_obj.paginator.page_range %}
        {% if page_obj.number == pg %}
          <li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% else %}
          <li><a href="?page={{ pg }}">{{ pg }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>
<!-- https://www.technovelty.org/web/skipping-pages-with-djangocorepaginator.html -->